final_project/Controllers/newsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using final_project.Models;
namespace final_project.Controllers
{
    public class newsController : Controller
    {
        // GET: news
        DBContext db = new DBContext();
        public ActionResult addnews()
        {
            if (Session["userid"] == null)
            {
               return RedirectToAction("login", "user");
            }
            SelectList cats = new SelectList(db.catalogs.ToList(),"id" ,"catname");
            ViewBag.cat = cats;
            return View();
        }

        [HttpPost]
        public ActionResult addnews(news n , HttpPostedFileBase img)
        {
            img.SaveAs(Server.MapPath($"~/attach/imgnews/{img.FileName}"));

            n.photo  = img.FileName;
            n.userid = (int)Session["userid"];
            n.newdate = DateTime.Now;
            db.news.Add(n);
            db.SaveChanges();
            return RedirectToAction("mynews");
        }

        public ActionResult mynews()
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("login", "user");
            }
            int userid = (int)Session["userid"];
            List<news> nes = db.news.Where(n => n.userid == userid).ToList();

            return View(nes);
        }


        public ActionResult allnews()
        {
            List<news> ln = db.news.ToList();
            return View(ln);
        }

        public ActionResult details(int id)
        {
            news ns = db.news.Where(n => n.id == id).SingleOrDefault();

            return View(ns);
        }

        public ActionResult delete (int id)
        {
            news ns = db.news.Where(n => n.id == id).SingleOrDefault();
            db.news.Remove(ns);
            db.SaveChanges();
            return RedirectToAction("mynews");
        }

        public ActionResult edit(int id)
        {
            SelectList sl = new SelectList(db.catalogs.ToList(), "id", "catname");
            ViewBag.cat = sl;
            news ns = db.news.Where(n => n.id == id).SingleOrDefault();

            return View(ns);
        }
        [HttpPost]
        public ActionResult edit(news n , HttpPostedFileBase img)
        {
            img.SaveAs(Server.MapPath($"~/attach/imgnews/{img.FileName}"));
            n.photo = img.FileName;
            n.userid = (int)Session["userid"];
            n.newdate = DateTime.Now;
            db.Entry(n).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("mynews");
        }

    }

}

final_project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("style", false)
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->

            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <div class="navbar-brand col-xs-offset-1 col-md-offset-0" >
                    <p>News ToDay</p>
                </div>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


                <ul class="nav navbar-nav navbar-right">
                    <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("AllNews", "allnews", "news")</li>

                    @{
                        if (Session["userid"] == null && Session["useradmin"] == null)
                        {

                            <li>@Html.ActionLink("Register", "register", "user")</li>
                            <li>@Html.ActionLink("Login", "login", "user")</li>

                        }
                        else if (Session["userid"] != null && Session["useradmin"] == null)
                        {

                            <li>@Html.ActionLink("MyNews", "mynews", "news")</li>
                            <li>@Html.ActionLink("Profile", "profile", "user")</li>
                            <li>@Html.ActionLink("logout", "logout", "user")</li>
                        }

                        else if (Session["useradmin"] != null && Session["userid"] == null)
                        {
                            <li>@Html.ActionLink("AdminPage", "AdminPage", "admin")</li>
                            <li>@Html.ActionLink("logout", "logout", "user")</li>

                        }

                    }
                </ul>
                

                <ul class="icons ">
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div class="container-fluid ">
        @RenderBody()
        <footer>
            <p class="text-center">&copy; 2021 -By <strong>Aya Ahmed</strong></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>